String htmlData="<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"  <meta charset='UTF-8'>"
"  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
" <title>NODEMCU Car Control</title>"
"  <style>"
"    .section{"
"      border: 1px solid #111;"
"      padding: 20px;"
"      margin: 20px;"
"    }"
"    .switch {"
"      position: relative;"
"      display: inline-block;"
"     width: 60px;"
"      height: 34px;"
"    }"
"    .switch input {"
"      opacity: 0;"
"      width: 0;"
"      height: 0;"
"    }"
"   .slider {"
"      position: absolute;"
"      cursor: pointer;"
"      top: 0;"
"      left: 0;"
"      right: 0;"
"      bottom: 0;"
"      background-color: #ccc;"
"      -webkit-transition: .4s;"
"      transition: .4s;"
"    }"
"    .slider:before {"
"      position: absolute;"
"      content: '';"
"      height: 26px;"
"      width: 26px;"
"      left: 4px;"
"      bottom: 4px;"
"      background-color: white;"
"      -webkit-transition: .4s;"
"      transition: .4s;"
"    }"
"    input:checked+.slider {"
"      background-color: #2196F3;"
"    }"
"    input:focus+.slider {"
"      box-shadow: 0 0 1px #2196F3;"
"    }"
"    input:checked+.slider:before {"
"      -webkit-transform: translateX(26px);"
"      -ms-transform: translateX(26px);"
"      transform: translateX(26px);"
"    }"
"    .slider.round {"
"      border-radius: 34px;"
"    }"
"    .slider.round:before {"
"      border-radius: 50%;"
"    }"
"    #pwmValue {"
"      max-width: 40px;"
"    }"

"    .slidecontainer {"
"      width: 100%;"
"      text-align: center;"
"    }"
"    .servo-slider {"
"      -webkit-appearance: none;"
"      width: 70%;"
"      height: 25px;"
"      background: #d3d3d3;"
"      outline: none;"
"      opacity: 0.7;"
"      -webkit-transition: .2s;"
"      transition: opacity .2s;"
"    }"
"    .servo-slider:hover {"
"      opacity: 1;"
"    }"
"    .servo-slider::-webkit-slider-thumb {"
"      -webkit-appearance: none;"
"      appearance: none;"
"      width: 25px;"
"      height: 25px;"
"      background: #4CAF50;"
"      cursor: pointer;"
"    }"
"    .servo-slider::-moz-range-thumb {"
"      width: 25px;"
"      height: 25px;"
"      background: #4CAF50;"
"      cursor: pointer;"
"    }"
"  </style>"
"</head>"



"<body>"

"  <div style='text-align: center;'>"
"    <div class='section'>"
"     <h3>Control Car</h3>"
"     <input onkeypress='car_input_change(event)' id='car_input' type='text' autofocus>"
"     <input onchange='car_pwm_input_change()' id='pwmValue' placeholder='PWM' value='100' type='text'>"
"     <p id='car_input_direction'></p>"
"    </div>"
"    <div class='section'>"
"      <h3>UV Switch</h3>"
"      <label class='switch' style='margin-left: 10px;'>"
"        <input onclick='uv_switch()' id='uv_switch_id' type='checkbox'>"
"        <span class='slider round'></span>"
"      </label>"
"    </div>"
"    <div class='section'>"
"      <div class='slidecontainer'>"
"        <p style='margin: 20px;font-size: 20px;'>Control Servo 1</p>"
"        <input id='servo-1' type='range' min='1' max='180' step='1' value='90' class='servo-slider'></input>"
"        <p>Value: '<span style='font-weight: 900;' id='value-1'>--</span>' degree</p>"
"      </div>"
"      <div class='slidecontainer'>"
"        <p style='margin: 20px;font-size: 20px;'>Control Servo 2</p>"
"        <input id='servo-2' type='range' min='1' max='180' step='1' value='90' class='servo-slider'></input>"
"        <p>Value: '<span style='font-weight: 900;' id='value-2'>--</span>' degree</p>"
"      </div>"
"      <div class='slidecontainer'>"
"        <p style='margin: 20px;font-size: 20px;'>Control Servo 3</p>"
"        <input id='servo-3' type='range' min='1' max='180' step='1' value='90' class='servo-slider'></input>"
"        <p>Value: '<span style='font-weight: 900;' id='value-3'>--</span>' degree</p>"
"      </div>"
"      <div class='slidecontainer'>"
"        <p style='margin: 20px;font-size: 20px;'>Control Servo 4</p>"
"        <input id='servo-4' type='range' min='1' max='180' step='1' value='90' class='servo-slider'></input>"
"        <p>Value: '<span style='font-weight: 900;' id='value-4'>--</span>' degree</p>"
"      </div>"
"    </div>"
"  </div>"

"  <script>"
"    var carInputEvent = document.getElementById('car_input');"
"    var UVSwitchFlag = 0;"
"    var pwmVal = 100;"
"    var currentDirection = 'forward';"
"    var canSendFlag = true;"
"    function car_input_change(event) {"
"      var x = event.which || event.keyCode;"
"      if (x === 119 || x === 87) {"
"        document.getElementById('car_input_direction').innerHTML = 'Forward';"
"        sendData('forward');"
"      } else if (x === 115 || x === 83) {"
"        document.getElementById('car_input_direction').innerHTML = 'Backward';"
"        sendData('backward');"
"      } else if (x === 97 || x === 65) {"
"        document.getElementById('car_input_direction').innerHTML = 'Left';"
"        sendData('left');"
"      } else if (x === 100 || x === 68) {"
"        document.getElementById('car_input_direction').innerHTML = 'Right';"
"        sendData('right');"
"      } else if (x === 113 || x === 81) {"
"        document.getElementById('car_input_direction').innerHTML = 'Go Forward';"
"        sendData('goforward');"
"      } else if (x === 101 || x === 69) {"
"        document.getElementById('car_input_direction').innerHTML = 'Stop!';"
"        sendData('stop');"
"      } else {"
"        document.getElementById('car_input_direction').innerHTML = 'Invalid!';"
"      }"
"      carInputEvent.value = '';"
"    }"

"    function car_pwm_input_change(){"
"      pwmVal=document.getElementById('pwmValue').value;"
"      if(pwmVal>250)"
"        pwmVal = 250;"
"      if(pwmVal<0 || pwmVal=='' || isNaN(pwmVal))"
"        pwmVal = 0;"
"      sendData(currentDirection);"
"    }"
    
"    function sendData(direction,isServo) {"
"      if(canSendFlag) {"
"      canSendFlag=false;"
"      var url = '/'+direction+'?pwm='+pwmVal+'&uvl='+UVSwitchFlag+'&servo='+allServoData;"
"      if(isServo)"
"        url+='&servoflag=1';"     
"      currentDirection = direction;" 
"      /*console.log(url);*/"
"      fetch(url)"
"        .then(res => {"
"          /*console.log(res);*/"
"          console.log('Sent!');"
"        }).catch(err => {"
"          /*console.log(err);*/"
"        })"
"     }"
"    }"

"    function uv_switch() {"
"     if (document.getElementById('uv_switch_id').checked)"
"        UVSwitchFlag = 1;"
"      else UVSwitchFlag = 0;"
"      sendData(currentDirection);"
"    }"

"    setInterval(() => {"
"      canSendFlag=true;"
"    }, 500);"

"/*Servo JS*/"
"    var servo1 = document.getElementById('servo-1');"
"    var servo2 = document.getElementById('servo-2');"
"    var servo3 = document.getElementById('servo-3');"
"    var servo4 = document.getElementById('servo-4');"
"    var allServoData='{90,90,90,90}';"

"    servo1.onclick = function () {"
"      document.getElementById('value-1').innerHTML = this.value;"
"      servoData();"
"    };"
"    servo2.onclick = function () {"
"      document.getElementById('value-2').innerHTML = this.value;"
"      servoData();"
"    };"
"    servo3.onclick = function () {"
"      document.getElementById('value-3').innerHTML = this.value;"
"      servoData();"
"    };"
"    servo4.onclick = function () {"
"      document.getElementById('value-4').innerHTML = this.value;"
"      servoData();"
"    };"

"    function servoData() {"
"      allServoData='{'+servo1.value+','+servo2.value+','+servo3.value+','+servo4.value+'}';"
"      sendData(currentDirection,true);"
"    }"
"  </script>"
"</body>"
"</html>";
